name: Cypress Tests with Percy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start API server
        run: npm run start:api &
        env:
          CI: true

      - name: Start back office server
        run: npm run start:backoffice &
        env:
          CI: true
      - name: Run Cypress tests with Percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy exec -- npx cypress run
